name: Example Pull Request Workflow
on: 
  push: 
    branches: 
      - master

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the greeting's time
        run: echo 'The time was now'